### PR TITLE
Draft document of KBase Conceptual Data Model

### PR DESCRIPTION
**Pull request by mlhenderson**
I had a whiteboard discussion with Adam and a few people from Berkeley just to wrap my head around this and kick off more discussions for how we think about biological data from a high level.  This will help frame how we think about our data types going forward.  This is a very rough draft and needs more work and input across the project.

### CODE REVIEW

**Comment by dangunter** [comment]
I don't think measurements are models (practically, not philosophically). Are you arguing to eliminate the term "measurement" or "model"? I think model is useful in the sense of "computer model", which is neither a biological concept nor a measurement (again, practically speaking).

**Comment by aparkin** [comment]
@dangunter @benbowen 
No-- not arguing for it. Acknowledging Ben's point and trying to say that there IS a practical definition of measurement for our cases but when we use it depends on on how "raw" our data upload is. Because if we upload raw spectra from mass spec and then infer protein levels from it, one could argue the computer model is what maps sets of m/z rations to sequences. 

For us it doesn't REALLY matter. The conceptualization is just to help us define data types so they they don't over-constrain a type so that the concept of something is linked to be the measurement of it. 

In the just mentioned case, I might say really the m/z and the sequence are both measurements practically-- of the important concept in our system "protein of identity X" for example. So we wouldn't assume the that protein X IS it sequence-- we would say both the mass spec and the sequences are measurements of protein X but that the sequences is an inference from the mass spec (by provenance). That way -- the single protein can point to multiple lines of evidence for its existence, abundance and sequence... so when I ask the system what has been measured about protein X I get a way to find all those measurements and I can then write tools that aggregate across those measurement to make a better inference of structure/abundance/function. 

The formality here is a little overdone, I admit. Really all I am saying is we should allow the biological objects about which we are speaking to have multiple measurements/assertions about their features (amounts, rates, shapes, positions, even identities). The motivation really is just that... identifying the abstract thing we are measuring (a transcript, a cell, a tissue, a population, a community) and then: 1)  allowing multiple measurements/inferences/assertions to be linked to it  2) relate the abstract object to other objects (transcript to the operon from which it was transcribed and the operon to the genome and cistrons in which it is contained and of which it is composed respectively; the cell to its population or family or taxonomy; etc. )

We also don't want multiple VERSIONS of the same "concept"... different versions of genome for example unless there is a very good reason.. or two different versions of the same protein (from the same strain of the same organism).. the protein is the same but the measurements might point to different possible sequences, etc. . 

As long we can do this all should be fine.

**Comment by pranjan77** [comment]
Looks good. It is very high level.  Where do entities like organs, organelles fit in? Also we have replicons/genes but where do promoters and other non-genic features fit in?

**Comment by aparkin** [comment]
@pranjan77 The replicons and genome features were left off the diagram for simplicity but they are there of course... Genome have replicons, replicons have features, some of which are transcriptional units, genes, promoters and regulatory motifs. 

Organs, organelles and tissues are more complicated. One route says that supercellular structures are really these are structured environments of a community of cells of the same taxon (mostly); and things like chloroplasts and mitochondria are environments that contain certain molecules and replicons, etc. So they environment is really a moniker for a bounded volume in which things can happen at at whose boundaries things may be transported or interact between environments. 

Another route says we should should have a true data model reflective of an ontology of anatomy. 

Either way works for me... just needs an implementation and to separate the ideal "object" from it measurements and to have the appropriate biological relationships to other objects (organelles to their cells, etc. )

**Comment by r2sunita** [comment]
I think "Genetic Variations" OR simply "Variations" concept need to be connected to the Genome entity concept and "Genome Assembly Version" need to be connected to the Assembly entity concept in the model.

**Comment by aparkin** [comment]
@r2sunita Yes-- we had variation on the board as well. But we need to be careful with that. A genome could be measured from an individual, a clonal population, or a "popgen" population, or a family. 
Variation of the sort you are talking about is likely about a popgen population or a family-controlled population and thus the concept is about variation across some sort of population. Its measurement is variation  of the genome. So yes-- there might be a linkage to the genome concept which could point to assemblies of individuals or variations sets... but the variation set would also have to point to what it was really about. For example, it could also be about an individual's cancer-- which would also be a variation set but a single "parent" genome.

**Comment by r2sunita** [comment]
Adam, I agree we need to be careful with about it - an individual versus a population makes a difference to the concept of genetic variations. Thinking about NGS - it's possible to detect mutations at a greater read depths (1000x or more) or even the GBS (genome by sequencing) experiments caring about the phased genome sequencing has the potential to uncover an individual's genetic variations. I agree, though, it's not a straight forward concept to integrate - we need to give deeper thoughts in capturing its relation to the genome, population, individual, assembly, assembly version; what are the most frequent "types" of use-cases. By "types" I mean the objective of sequencing experiments (whole genome vs partial genome and/or individual vs family vs population).

**Comment by vkcshl** [comment]
Regarding the scope of the logical concepts covered in this discussion and the iterative process leading to more robust data types for the next 2-3 years:

Is there a plan to (re)visit other related concepts, such as molecular & genetic interactions, biochemical reactions, pathway processes, pathway groups,  regulatory & interaction networks etc?

Is there a new/updated design document which attempts to define these concepts, and the biological/semantic relationships among them. We should perhaps pick a use-case driven approach and identify the broader set of services needed by the KBase community to drive the discussion around the  scope and nature of biological data-types in the specific context of KBase.

**Comment by mlhenderson** [comment]
@vkcshl To answer your question, in short yes we will definitely map out other areas.  The timeline for that and order will have to fit in with the schedule so that we are focusing on upcoming items, but absolutely we would expand this over time.

The definitions of the concepts are in a separate document that we would need to work on in addition to these diagrams.

The plan is to actually prototype something concrete by translating the diagrams into a physical data model with one or more use cases in order to evaluate the conceptual model.  Part of that will also be coming up with ways to transition as the model evolves.

I would greatly appreciate feedback on the model at this level if there are any problems or questions.

**Pull request merged**
