### PR TITLE
Improve list of graph technologies

### PR DESCRIPTION
**Pull request by dangunter**
Feel free to suggest additions.

### CODE REVIEW

**Comment by dangunter** [comment]
@mlhenderson , @psnovichkov You may be interested in these

**Comment by psnovichkov** [comment]
in what?
P.

**Comment by mlhenderson** [comment]
you mentioned elasticsearch and lucene but not solr

**Comment by dangunter** [comment]
Ok. You could add it too ..

**Comment by mlhenderson** [comment]
http://en.wikipedia.org/wiki/Graph_database has a comprehensive list and comparison chart of features.

Weaver is interesting, but in alpha.  http://weaver.systems

Titan guys came up with Fauna for graph processing.  http://thinkaurelius.github.io/faunus/

**Pull request merged**
